services:
  database:
    image: postgis/postgis:14-3.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD
      # No authentication for now...
      - POSTGRES_DB=stratiform
    user: postgres
    ports:
      - "54321:5432"
    volumes:
      - ./db_cluster:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 3
  gateway:
    image: nginx:mainline
    ports:
      - "8000:80"
    volumes:
      - ./gateway:/etc/nginx/conf.d:ro
  api:
    image: postgrest/postgrest:v9.0.0
    environment:
      - PGRST_DB_URI=postgresql://postgres:${POSTGRES_PASSWORD}@database:5432/stratiform
      - PGRST_DB_SCHEMAS=stratiform_api,storage
      - PGRST_DB_ANON_ROLE=postgres
      - PGRST_JWT_SECRET
    depends_on:
      gateway:
        condition: service_started
      database:
        condition: service_healthy
  storage_api:
    build: ./storage_api
    expose:
      - 5000
    environment:
      - ANON_KEY
      - SERVICE_KEY
      - TENANT_ID=stratiform
      - AWS_ACCESS_KEY_ID=$STORAGE_KEY
      - AWS_SECRET_ACCESS_KEY=$STORAGE_SECRET
      - REGION=shim
      - GLOBAL_S3_ENDPOINT=http://storage:9000
      - GLOBAL_S3_BUCKET=$STORAGE_BUCKET
      - PGRST_JWT_SECRET
      - POSTGREST_URL=http://api:3000
      # - PGRST_JWT_SECRET=$STRATIFORM_SECRET
      # - GLOBAL_S3_ENDPOINT=https://s3.amazonaws.com
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@database:5432/stratiform
      # - PGOPTIONS="-c search_path=storage,stratiform,public"
      - FILE_SIZE_LIMIT=50000000
      - STORAGE_BACKEND=s3
    depends_on:
      database:
        condition: service_healthy
      gateway:
        condition: service_started
  storage:
    # https://github.com/minio/minio/blob/master/docs/docker/README.md
    # For now, need to use a release prior to 10-29-2022, as the filesystem mode is now removed
    # https://min.io/docs/minio/linux/operations/install-deploy-manage/migrate-fs-gateway.html
    image: minio/minio:RELEASE.2022-10-24T18-35-07Z.fips
    command: server /data --address 0.0.0.0:9000 --console-address :9001 --config-dir /etc/minio
    volumes:
      - ./data:/data
    expose:
      - 9000
    networks:
      default:
        aliases:
          - ${STORAGE_BUCKET}.storage
    environment:
      - MINIO_ROOT_USER=$STORAGE_KEY
      - MINIO_ROOT_PASSWORD=$STORAGE_SECRET
      - MINIO_DOMAIN=storage
  createbuckets:
    image: minio/mc
    depends_on:
      - storage
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add storage http://storage:9000 ${STORAGE_KEY} ${STORAGE_SECRET};
      /usr/bin/mc mb storage/${STORAGE_BUCKET};
      exit 0;
      "
